export enum SkillTypeEnum {
  HTML = 'HTML',
  CSS = 'CSS',
  JAVASCRIPT = 'JAVASCRIPT',
  GIT = 'GIT',
  REACT = 'REACT',
  MATERIAL_UI = 'MATERIAL_UI',
  REACT_QUERY = 'REACT_QUERY',
  REDUX = 'REDUX',
  STYLED_COMPONENTS = 'STYLED_COMPONENTS',
  SASS = 'SASS'
}
